/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aviconics_devicelib_BodyControlCom */

#ifndef _Included_com_aviconics_devicelib_BodyControlCom
#define _Included_com_aviconics_devicelib_BodyControlCom
#ifdef __cplusplus
extern "C" {
#endif
#undef com_aviconics_devicelib_BodyControlCom_CONTROL_SET_LEFT_ARM_ANGLE
#define com_aviconics_devicelib_BodyControlCom_CONTROL_SET_LEFT_ARM_ANGLE 1L
#undef com_aviconics_devicelib_BodyControlCom_CONTROL_SET_RIGHT_ARM_ANGLE
#define com_aviconics_devicelib_BodyControlCom_CONTROL_SET_RIGHT_ARM_ANGLE 2L
#undef com_aviconics_devicelib_BodyControlCom_CONTROL_SET_NOD_ANGLE
#define com_aviconics_devicelib_BodyControlCom_CONTROL_SET_NOD_ANGLE 3L
#undef com_aviconics_devicelib_BodyControlCom_CONTROL_SET_SHAKE_ANGLE
#define com_aviconics_devicelib_BodyControlCom_CONTROL_SET_SHAKE_ANGLE 4L
#undef com_aviconics_devicelib_BodyControlCom_CONTROL_CMD_MAX
#define com_aviconics_devicelib_BodyControlCom_CONTROL_CMD_MAX 5L
#undef com_aviconics_devicelib_BodyControlCom_CMD_PARAM_POS
#define com_aviconics_devicelib_BodyControlCom_CMD_PARAM_POS 5L
/*
 * Class:     com_aviconics_devicelib_BodyControlCom
 * Method:    native_bodyCom_msg_send
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_aviconics_devicelib_BodyControlCom_native_1bodyCom_1msg_1send
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_aviconics_devicelib_BodyControlCom
 * Method:    native_bodyCom_init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_aviconics_devicelib_BodyControlCom_native_1bodyCom_1init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_aviconics_devicelib_BodyControlCom
 * Method:    native_bodyCom_exit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aviconics_devicelib_BodyControlCom_native_1bodyCom_1exit
  (JNIEnv *, jobject);

/*
 * Class:     com_aviconics_devicelib_BodyControlCom
 * Method:    native_flexible_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aviconics_devicelib_BodyControlCom_native_1flexible_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_aviconics_devicelib_BodyControlCom
 * Method:    native_flexible
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_aviconics_devicelib_BodyControlCom_native_1flexible
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_aviconics_devicelib_BodyControlCom
 * Method:    native_flexible_state
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aviconics_devicelib_BodyControlCom_native_1flexible_1state
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
