/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aviconics_devicelib_SubControlBoard */

#ifndef _Included_com_aviconics_devicelib_SubControlBoard
#define _Included_com_aviconics_devicelib_SubControlBoard
#ifdef __cplusplus
extern "C" {
#endif
#undef com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_SET_FORWARD
#define com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_SET_FORWARD 1L
#undef com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_SET_BACKUP
#define com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_SET_BACKUP 2L
#undef com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_SET_LEFT
#define com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_SET_LEFT 3L
#undef com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_SET_RIGHT
#define com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_SET_RIGHT 4L
#undef com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_SET_BRAKE
#define com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_SET_BRAKE 5L
#undef com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_GET_COMPASS
#define com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_GET_COMPASS 6L
#undef com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_GET_GYROSCOPE
#define com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_GET_GYROSCOPE 7L
#undef com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_GET_ULTRWAVE
#define com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_GET_ULTRWAVE 8L
#undef com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_GET_FALLSTATUS
#define com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_GET_FALLSTATUS 9L
#undef com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_GET_BATTERYSTATUS
#define com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_GET_BATTERYSTATUS 16L
#undef com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_MAX
#define com_aviconics_devicelib_SubControlBoard_CHASSIC_CMD_MAX 17L
#undef com_aviconics_devicelib_SubControlBoard_HEAD_CMD_SET_EXPRESSION
#define com_aviconics_devicelib_SubControlBoard_HEAD_CMD_SET_EXPRESSION 0L
#undef com_aviconics_devicelib_SubControlBoard_HEAD_CMD_MAX
#define com_aviconics_devicelib_SubControlBoard_HEAD_CMD_MAX 1L
#undef com_aviconics_devicelib_SubControlBoard_CMD_PARAM_POS
#define com_aviconics_devicelib_SubControlBoard_CMD_PARAM_POS 4L
/*
 * Class:     com_aviconics_devicelib_SubControlBoard
 * Method:    native_subBoard_msg_send
 * Signature: (Ljava/lang/String;I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_aviconics_devicelib_SubControlBoard_native_1subBoard_1msg_1send
  (JNIEnv *, jobject, jstring, jint, jbyteArray, jint);

/*
 * Class:     com_aviconics_devicelib_SubControlBoard
 * Method:    native_subBoard_init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aviconics_devicelib_SubControlBoard_native_1subBoard_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_aviconics_devicelib_SubControlBoard
 * Method:    native_subBoard_exit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_aviconics_devicelib_SubControlBoard_native_1subBoard_1exit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
